//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GDEWebService.AssessmentStructureWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AssessmentStructureWSSoap", Namespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScorisWSReceipt))]
    public partial class AssessmentStructureWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkSchemeAnswerOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkSchemeStructureOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AssessmentStructureWS() {
            this.Url = global::GDEWebService.Properties.Settings.Default.GDEWebService_AssessmentStructureWS_AssessmentStructureWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProductCompletedEventHandler ProductCompleted;
        
        /// <remarks/>
        public event LayoutCompletedEventHandler LayoutCompleted;
        
        /// <remarks/>
        public event MarkSchemeAnswerCompletedEventHandler MarkSchemeAnswerCompleted;
        
        /// <remarks/>
        public event MarkSchemeStructureCompletedEventHandler MarkSchemeStructureCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03/Product", RequestNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", ResponseNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductReceipt Product(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")] ProductArguments ProductArguments) {
            object[] results = this.Invoke("Product", new object[] {
                        RMKey,
                        ProductArguments});
            return ((ProductReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void ProductAsync(string RMKey, ProductArguments ProductArguments) {
            this.ProductAsync(RMKey, ProductArguments, null);
        }
        
        /// <remarks/>
        public void ProductAsync(string RMKey, ProductArguments ProductArguments, object userState) {
            if ((this.ProductOperationCompleted == null)) {
                this.ProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductOperationCompleted);
            }
            this.InvokeAsync("Product", new object[] {
                        RMKey,
                        ProductArguments}, this.ProductOperationCompleted, userState);
        }
        
        private void OnProductOperationCompleted(object arg) {
            if ((this.ProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductCompleted(this, new ProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03/Layout", RequestNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", ResponseNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LayoutReceipt Layout(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Layout")] LayoutArguments LayoutArguments) {
            object[] results = this.Invoke("Layout", new object[] {
                        RMKey,
                        LayoutArguments});
            return ((LayoutReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void LayoutAsync(string RMKey, LayoutArguments LayoutArguments) {
            this.LayoutAsync(RMKey, LayoutArguments, null);
        }
        
        /// <remarks/>
        public void LayoutAsync(string RMKey, LayoutArguments LayoutArguments, object userState) {
            if ((this.LayoutOperationCompleted == null)) {
                this.LayoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayoutOperationCompleted);
            }
            this.InvokeAsync("Layout", new object[] {
                        RMKey,
                        LayoutArguments}, this.LayoutOperationCompleted, userState);
        }
        
        private void OnLayoutOperationCompleted(object arg) {
            if ((this.LayoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayoutCompleted(this, new LayoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03/MarkSchemeAnsw" +
            "er", RequestNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", ResponseNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MarkSchemeAnswerReceipt MarkSchemeAnswer(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeAnswer")] MarkSchemeAnswerArguments MarkSchemeAnswerArguments) {
            object[] results = this.Invoke("MarkSchemeAnswer", new object[] {
                        RMKey,
                        MarkSchemeAnswerArguments});
            return ((MarkSchemeAnswerReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void MarkSchemeAnswerAsync(string RMKey, MarkSchemeAnswerArguments MarkSchemeAnswerArguments) {
            this.MarkSchemeAnswerAsync(RMKey, MarkSchemeAnswerArguments, null);
        }
        
        /// <remarks/>
        public void MarkSchemeAnswerAsync(string RMKey, MarkSchemeAnswerArguments MarkSchemeAnswerArguments, object userState) {
            if ((this.MarkSchemeAnswerOperationCompleted == null)) {
                this.MarkSchemeAnswerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkSchemeAnswerOperationCompleted);
            }
            this.InvokeAsync("MarkSchemeAnswer", new object[] {
                        RMKey,
                        MarkSchemeAnswerArguments}, this.MarkSchemeAnswerOperationCompleted, userState);
        }
        
        private void OnMarkSchemeAnswerOperationCompleted(object arg) {
            if ((this.MarkSchemeAnswerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkSchemeAnswerCompleted(this, new MarkSchemeAnswerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03/MarkSchemeStru" +
            "cture", RequestNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", ResponseNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MarkSchemeStructureReceipt MarkSchemeStructure(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")] MarkSchemeStructureArguments MarkSchemeStructureArguments) {
            object[] results = this.Invoke("MarkSchemeStructure", new object[] {
                        RMKey,
                        MarkSchemeStructureArguments});
            return ((MarkSchemeStructureReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void MarkSchemeStructureAsync(string RMKey, MarkSchemeStructureArguments MarkSchemeStructureArguments) {
            this.MarkSchemeStructureAsync(RMKey, MarkSchemeStructureArguments, null);
        }
        
        /// <remarks/>
        public void MarkSchemeStructureAsync(string RMKey, MarkSchemeStructureArguments MarkSchemeStructureArguments, object userState) {
            if ((this.MarkSchemeStructureOperationCompleted == null)) {
                this.MarkSchemeStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkSchemeStructureOperationCompleted);
            }
            this.InvokeAsync("MarkSchemeStructure", new object[] {
                        RMKey,
                        MarkSchemeStructureArguments}, this.MarkSchemeStructureOperationCompleted, userState);
        }
        
        private void OnMarkSchemeStructureOperationCompleted(object arg) {
            if ((this.MarkSchemeStructureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkSchemeStructureCompleted(this, new MarkSchemeStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03/Ping", RequestNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", ResponseNamespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class ProductArguments {
        
        private ProductArgumentsQuestionPaper questionPaperField;
        
        private ProductArgumentsSession sessionField;
        
        private ProductArgumentsProduct productField;
        
        private ProductArgumentsExam examField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductArgumentsQuestionPaper QuestionPaper {
            get {
                return this.questionPaperField;
            }
            set {
                this.questionPaperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductArgumentsSession Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductArgumentsProduct Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductArgumentsExam Exam {
            get {
                return this.examField;
            }
            set {
                this.examField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class ProductArgumentsQuestionPaper {
        
        private string barcodeField;
        
        private string markingTypeField;
        
        private string nameField;
        
        private int pageCountField;
        
        private bool pageCountFieldSpecified;
        
        private string questionPaperIdentifierField;
        
        private string questionPaperPartNameField;
        
        private string syllabusCodeField;
        
        private QuestionPaperPageCharacteristic[] questionPaperPageCharacteristicsField;
        
        private QuestionPaperCharacteristic[] questionPaperCharacteristicsField;
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkingType {
            get {
                return this.markingTypeField;
            }
            set {
                this.markingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageCountSpecified {
            get {
                return this.pageCountFieldSpecified;
            }
            set {
                this.pageCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionPaperIdentifier {
            get {
                return this.questionPaperIdentifierField;
            }
            set {
                this.questionPaperIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string QuestionPaperPartName {
            get {
                return this.questionPaperPartNameField;
            }
            set {
                this.questionPaperPartNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SyllabusCode {
            get {
                return this.syllabusCodeField;
            }
            set {
                this.syllabusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public QuestionPaperPageCharacteristic[] QuestionPaperPageCharacteristics {
            get {
                return this.questionPaperPageCharacteristicsField;
            }
            set {
                this.questionPaperPageCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public QuestionPaperCharacteristic[] QuestionPaperCharacteristics {
            get {
                return this.questionPaperCharacteristicsField;
            }
            set {
                this.questionPaperCharacteristicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class QuestionPaperPageCharacteristic {
        
        private string descriptorField;
        
        private int pageField;
        
        /// <remarks/>
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        public int Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MarkScheme", Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class MarkScheme1 {
        
        private int markSchemeIdentifierField;
        
        private string nameField;
        
        private int markTypeIdentifierField;
        
        private int markingItemIdentifierField;
        
        private bool markingItemIdentifierFieldSpecified;
        
        private int markingClusterIdentifierField;
        
        private bool markingClusterIdentifierFieldSpecified;
        
        private int sequenceField;
        
        private bool wholenumberIndicatorField;
        
        private decimal numericMarkingToleranceField;
        
        private bool numericMarkingToleranceFieldSpecified;
        
        private bool mandateCommentField;
        
        private short reuseRIGSequenceField;
        
        public MarkScheme1() {
            this.mandateCommentField = false;
        }
        
        /// <remarks/>
        public int MarkSchemeIdentifier {
            get {
                return this.markSchemeIdentifierField;
            }
            set {
                this.markSchemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int MarkTypeIdentifier {
            get {
                return this.markTypeIdentifierField;
            }
            set {
                this.markTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int MarkingItemIdentifier {
            get {
                return this.markingItemIdentifierField;
            }
            set {
                this.markingItemIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarkingItemIdentifierSpecified {
            get {
                return this.markingItemIdentifierFieldSpecified;
            }
            set {
                this.markingItemIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int MarkingClusterIdentifier {
            get {
                return this.markingClusterIdentifierField;
            }
            set {
                this.markingClusterIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarkingClusterIdentifierSpecified {
            get {
                return this.markingClusterIdentifierFieldSpecified;
            }
            set {
                this.markingClusterIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public bool WholenumberIndicator {
            get {
                return this.wholenumberIndicatorField;
            }
            set {
                this.wholenumberIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumericMarkingTolerance {
            get {
                return this.numericMarkingToleranceField;
            }
            set {
                this.numericMarkingToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumericMarkingToleranceSpecified {
            get {
                return this.numericMarkingToleranceFieldSpecified;
            }
            set {
                this.numericMarkingToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MandateComment {
            get {
                return this.mandateCommentField;
            }
            set {
                this.mandateCommentField = value;
            }
        }
        
        /// <remarks/>
        public short ReuseRIGSequence {
            get {
                return this.reuseRIGSequenceField;
            }
            set {
                this.reuseRIGSequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="MarkOption", Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class MarkOption1 {
        
        private int markOptionIdentifierField;
        
        private string displayLabelField;
        
        private string bandField;
        
        private decimal numericValueField;
        
        private bool numericValueFieldSpecified;
        
        /// <remarks/>
        public int MarkOptionIdentifier {
            get {
                return this.markOptionIdentifierField;
            }
            set {
                this.markOptionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayLabel {
            get {
                return this.displayLabelField;
            }
            set {
                this.displayLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Band {
            get {
                return this.bandField;
            }
            set {
                this.bandField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumericValue {
            get {
                return this.numericValueField;
            }
            set {
                this.numericValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumericValueSpecified {
            get {
                return this.numericValueFieldSpecified;
            }
            set {
                this.numericValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class MarkType {
        
        private int markTypeIdentifierField;
        
        private string nameField;
        
        private string descriptionField;
        
        private decimal maximumNumericMarkField;
        
        private bool maximumNumericMarkFieldSpecified;
        
        private decimal minimumNumericMarkField;
        
        private bool minimumNumericMarkFieldSpecified;
        
        private decimal stepField;
        
        private bool stepFieldSpecified;
        
        private bool numericIndicatorField;
        
        private bool allowNoResponseField;
        
        private bool allowNoResponseFieldSpecified;
        
        private decimal defaultMarkField;
        
        private bool defaultMarkFieldSpecified;
        
        private int defaultMarkOptionIdentifierField;
        
        private bool defaultMarkOptionIdentifierFieldSpecified;
        
        private MarkOption1[] markOptionsField;
        
        private string displayLabelField;
        
        private string markTypeVarietyField;
        
        /// <remarks/>
        public int MarkTypeIdentifier {
            get {
                return this.markTypeIdentifierField;
            }
            set {
                this.markTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaximumNumericMark {
            get {
                return this.maximumNumericMarkField;
            }
            set {
                this.maximumNumericMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumNumericMarkSpecified {
            get {
                return this.maximumNumericMarkFieldSpecified;
            }
            set {
                this.maximumNumericMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal MinimumNumericMark {
            get {
                return this.minimumNumericMarkField;
            }
            set {
                this.minimumNumericMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumNumericMarkSpecified {
            get {
                return this.minimumNumericMarkFieldSpecified;
            }
            set {
                this.minimumNumericMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StepSpecified {
            get {
                return this.stepFieldSpecified;
            }
            set {
                this.stepFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool NumericIndicator {
            get {
                return this.numericIndicatorField;
            }
            set {
                this.numericIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public bool AllowNoResponse {
            get {
                return this.allowNoResponseField;
            }
            set {
                this.allowNoResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowNoResponseSpecified {
            get {
                return this.allowNoResponseFieldSpecified;
            }
            set {
                this.allowNoResponseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal DefaultMark {
            get {
                return this.defaultMarkField;
            }
            set {
                this.defaultMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultMarkSpecified {
            get {
                return this.defaultMarkFieldSpecified;
            }
            set {
                this.defaultMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int DefaultMarkOptionIdentifier {
            get {
                return this.defaultMarkOptionIdentifierField;
            }
            set {
                this.defaultMarkOptionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultMarkOptionIdentifierSpecified {
            get {
                return this.defaultMarkOptionIdentifierFieldSpecified;
            }
            set {
                this.defaultMarkOptionIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MarkOption1[] MarkOptions {
            get {
                return this.markOptionsField;
            }
            set {
                this.markOptionsField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayLabel {
            get {
                return this.displayLabelField;
            }
            set {
                this.displayLabelField = value;
            }
        }
        
        /// <remarks/>
        public string MarkTypeVariety {
            get {
                return this.markTypeVarietyField;
            }
            set {
                this.markTypeVarietyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class MarkingItem {
        
        private int markingItemIdentifierField;
        
        private string displayLabelField;
        
        private string questionNumberField;
        
        private string questionPartField;
        
        private int markingClusterIdentifierField;
        
        private int imageClusterIdentifierField;
        
        private bool imageClusterIdentifierFieldSpecified;
        
        private int sequenceField;
        
        private string elementMarkTypeField;
        
        private string questionTagField;
        
        private short reuseRIGSequenceField;
        
        /// <remarks/>
        public int MarkingItemIdentifier {
            get {
                return this.markingItemIdentifierField;
            }
            set {
                this.markingItemIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayLabel {
            get {
                return this.displayLabelField;
            }
            set {
                this.displayLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionNumber {
            get {
                return this.questionNumberField;
            }
            set {
                this.questionNumberField = value;
            }
        }
        
        /// <remarks/>
        public string QuestionPart {
            get {
                return this.questionPartField;
            }
            set {
                this.questionPartField = value;
            }
        }
        
        /// <remarks/>
        public int MarkingClusterIdentifier {
            get {
                return this.markingClusterIdentifierField;
            }
            set {
                this.markingClusterIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int ImageClusterIdentifier {
            get {
                return this.imageClusterIdentifierField;
            }
            set {
                this.imageClusterIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageClusterIdentifierSpecified {
            get {
                return this.imageClusterIdentifierFieldSpecified;
            }
            set {
                this.imageClusterIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string ElementMarkType {
            get {
                return this.elementMarkTypeField;
            }
            set {
                this.elementMarkTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionTag {
            get {
                return this.questionTagField;
            }
            set {
                this.questionTagField = value;
            }
        }
        
        /// <remarks/>
        public short ReuseRIGSequence {
            get {
                return this.reuseRIGSequenceField;
            }
            set {
                this.reuseRIGSequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class MarkingCluster {
        
        private int markingClusterIdentifierField;
        
        private string nameField;
        
        private int sequenceField;
        
        private int maximumExpectedResponsesField;
        
        private bool maximumExpectedResponsesFieldSpecified;
        
        private int parentMarkingClusterIdentifierField;
        
        private short reuseRIGSequenceField;
        
        private System.Nullable<int> maxQnsField;
        
        private System.Nullable<int> secMinField;
        
        /// <remarks/>
        public int MarkingClusterIdentifier {
            get {
                return this.markingClusterIdentifierField;
            }
            set {
                this.markingClusterIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumExpectedResponses {
            get {
                return this.maximumExpectedResponsesField;
            }
            set {
                this.maximumExpectedResponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumExpectedResponsesSpecified {
            get {
                return this.maximumExpectedResponsesFieldSpecified;
            }
            set {
                this.maximumExpectedResponsesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ParentMarkingClusterIdentifier {
            get {
                return this.parentMarkingClusterIdentifierField;
            }
            set {
                this.parentMarkingClusterIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public short ReuseRIGSequence {
            get {
                return this.reuseRIGSequenceField;
            }
            set {
                this.reuseRIGSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxQns {
            get {
                return this.maxQnsField;
            }
            set {
                this.maxQnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SecMin {
            get {
                return this.secMinField;
            }
            set {
                this.secMinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class ExceptionType {
        
        private string descriptorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class SampleRule {
        
        private string ruleNameField;
        
        private int lowerField;
        
        private int sampleTriggerField;
        
        private int sampleTriggerTypeField;
        
        private int sampleSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
        
        /// <remarks/>
        public int Lower {
            get {
                return this.lowerField;
            }
            set {
                this.lowerField = value;
            }
        }
        
        /// <remarks/>
        public int SampleTrigger {
            get {
                return this.sampleTriggerField;
            }
            set {
                this.sampleTriggerField = value;
            }
        }
        
        /// <remarks/>
        public int SampleTriggerType {
            get {
                return this.sampleTriggerTypeField;
            }
            set {
                this.sampleTriggerTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SampleSize {
            get {
                return this.sampleSizeField;
            }
            set {
                this.sampleSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="E-StandardisationCreationTarget", Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class EStandardisationCreationTarget {
        
        private string markingModeNameField;
        
        private int targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkingModeName {
            get {
                return this.markingModeNameField;
            }
            set {
                this.markingModeNameField = value;
            }
        }
        
        /// <remarks/>
        public int Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class Annotation {
        
        private string descriptorField;
        
        private System.Nullable<long> markTypeIdentifierField;
        
        private bool markTypeIdentifierFieldSpecified;
        
        private System.Nullable<decimal> numericValueField;
        
        private bool numericValueFieldSpecified;
        
        private string shortcutKeyField;
        
        private string singleAnnotationMarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> MarkTypeIdentifier {
            get {
                return this.markTypeIdentifierField;
            }
            set {
                this.markTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarkTypeIdentifierSpecified {
            get {
                return this.markTypeIdentifierFieldSpecified;
            }
            set {
                this.markTypeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> NumericValue {
            get {
                return this.numericValueField;
            }
            set {
                this.numericValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumericValueSpecified {
            get {
                return this.numericValueFieldSpecified;
            }
            set {
                this.numericValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShortcutKey {
            get {
                return this.shortcutKeyField;
            }
            set {
                this.shortcutKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SingleAnnotationMark {
            get {
                return this.singleAnnotationMarkField;
            }
            set {
                this.singleAnnotationMarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class Characteristic {
        
        private string descriptorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class QuestionItemGroup {
        
        private long questionItemGroupIdentifierField;
        
        private string nameField;
        
        private int defaultGraceField;
        
        private bool eStandardisationIndicatorField;
        
        private int expectedMaxResponsesField;
        
        private string markingApplicationIdentifierField;
        
        private int markingCountField;
        
        private int maximumCacheLimitField;
        
        private int maximumConcurrentMarkingLimitField;
        
        private string markingStartTimeField;
        
        private string markingEndTimeField;
        
        private int remarkPercentageField;
        
        private bool remarkPercentageFieldSpecified;
        
        private string objectTypeField;
        
        private int markingToleranceField;
        
        private bool markingToleranceFieldSpecified;
        
        private int tMDToleranceField;
        
        private bool tMDToleranceFieldSpecified;
        
        private bool showQuestionTotalsField;
        
        private bool showQuestionTotalsFieldSpecified;
        
        private System.DateTime markingStartDateField;
        
        private bool markingStartDateFieldSpecified;
        
        private System.DateTime markingEndDateField;
        
        private bool markingEndDateFieldSpecified;
        
        private string questionItemGroupLinkIdentifierField;
        
        private int groupingIdentifierField;
        
        private bool groupingIdentifierFieldSpecified;
        
        private System.Nullable<int> maxQnsField;
        
        private Characteristic[] characteristicsField;
        
        private Annotation[] annotationsField;
        
        private EStandardisationCreationTarget[] eStandardisationCreationTargetsField;
        
        private SampleRule[] sampleRulesField;
        
        private ExceptionType[] exceptionTypesField;
        
        /// <remarks/>
        public long QuestionItemGroupIdentifier {
            get {
                return this.questionItemGroupIdentifierField;
            }
            set {
                this.questionItemGroupIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int DefaultGrace {
            get {
                return this.defaultGraceField;
            }
            set {
                this.defaultGraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-StandardisationIndicator")]
        public bool EStandardisationIndicator {
            get {
                return this.eStandardisationIndicatorField;
            }
            set {
                this.eStandardisationIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public int ExpectedMaxResponses {
            get {
                return this.expectedMaxResponsesField;
            }
            set {
                this.expectedMaxResponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkingApplicationIdentifier {
            get {
                return this.markingApplicationIdentifierField;
            }
            set {
                this.markingApplicationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int MarkingCount {
            get {
                return this.markingCountField;
            }
            set {
                this.markingCountField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumCacheLimit {
            get {
                return this.maximumCacheLimitField;
            }
            set {
                this.maximumCacheLimitField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumConcurrentMarkingLimit {
            get {
                return this.maximumConcurrentMarkingLimitField;
            }
            set {
                this.maximumConcurrentMarkingLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkingStartTime {
            get {
                return this.markingStartTimeField;
            }
            set {
                this.markingStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkingEndTime {
            get {
                return this.markingEndTimeField;
            }
            set {
                this.markingEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Re-markPercentage")]
        public int RemarkPercentage {
            get {
                return this.remarkPercentageField;
            }
            set {
                this.remarkPercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemarkPercentageSpecified {
            get {
                return this.remarkPercentageFieldSpecified;
            }
            set {
                this.remarkPercentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ObjectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        public int MarkingTolerance {
            get {
                return this.markingToleranceField;
            }
            set {
                this.markingToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarkingToleranceSpecified {
            get {
                return this.markingToleranceFieldSpecified;
            }
            set {
                this.markingToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TMDTolerance {
            get {
                return this.tMDToleranceField;
            }
            set {
                this.tMDToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TMDToleranceSpecified {
            get {
                return this.tMDToleranceFieldSpecified;
            }
            set {
                this.tMDToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ShowQuestionTotals {
            get {
                return this.showQuestionTotalsField;
            }
            set {
                this.showQuestionTotalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShowQuestionTotalsSpecified {
            get {
                return this.showQuestionTotalsFieldSpecified;
            }
            set {
                this.showQuestionTotalsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MarkingStartDate {
            get {
                return this.markingStartDateField;
            }
            set {
                this.markingStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarkingStartDateSpecified {
            get {
                return this.markingStartDateFieldSpecified;
            }
            set {
                this.markingStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MarkingEndDate {
            get {
                return this.markingEndDateField;
            }
            set {
                this.markingEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarkingEndDateSpecified {
            get {
                return this.markingEndDateFieldSpecified;
            }
            set {
                this.markingEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionItemGroupLinkIdentifier {
            get {
                return this.questionItemGroupLinkIdentifierField;
            }
            set {
                this.questionItemGroupLinkIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int GroupingIdentifier {
            get {
                return this.groupingIdentifierField;
            }
            set {
                this.groupingIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupingIdentifierSpecified {
            get {
                return this.groupingIdentifierFieldSpecified;
            }
            set {
                this.groupingIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxQns {
            get {
                return this.maxQnsField;
            }
            set {
                this.maxQnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Characteristic[] Characteristics {
            get {
                return this.characteristicsField;
            }
            set {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Annotation[] Annotations {
            get {
                return this.annotationsField;
            }
            set {
                this.annotationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("E-StandardisationCreationTargets")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public EStandardisationCreationTarget[] EStandardisationCreationTargets {
            get {
                return this.eStandardisationCreationTargetsField;
            }
            set {
                this.eStandardisationCreationTargetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SampleRule[] SampleRules {
            get {
                return this.sampleRulesField;
            }
            set {
                this.sampleRulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExceptionType[] ExceptionTypes {
            get {
                return this.exceptionTypesField;
            }
            set {
                this.exceptionTypesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeAnswer")]
    public partial class MarkOption {
        
        private int markOptionIdentifierField;
        
        private decimal numericValueField;
        
        private bool numericValueFieldSpecified;
        
        /// <remarks/>
        public int MarkOptionIdentifier {
            get {
                return this.markOptionIdentifierField;
            }
            set {
                this.markOptionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumericValue {
            get {
                return this.numericValueField;
            }
            set {
                this.numericValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumericValueSpecified {
            get {
                return this.numericValueFieldSpecified;
            }
            set {
                this.numericValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeAnswer")]
    public partial class MarkScheme {
        
        private int markSchemeIdentifierField;
        
        private int markTypeIdentifierField;
        
        private MarkOption[] markOptionsField;
        
        /// <remarks/>
        public int MarkSchemeIdentifier {
            get {
                return this.markSchemeIdentifierField;
            }
            set {
                this.markSchemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int MarkTypeIdentifier {
            get {
                return this.markTypeIdentifierField;
            }
            set {
                this.markTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MarkOption[] MarkOptions {
            get {
                return this.markOptionsField;
            }
            set {
                this.markOptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Layout")]
    public partial class ImageZone {
        
        private int imageZoneIdentifierField;
        
        private string nameField;
        
        private int sequenceField;
        
        private int sourcePageField;
        
        private decimal heightField;
        
        private decimal leftField;
        
        private decimal topField;
        
        private decimal widthField;
        
        private string imageFileFormatField;
        
        private int outputPageNumberField;
        
        /// <remarks/>
        public int ImageZoneIdentifier {
            get {
                return this.imageZoneIdentifierField;
            }
            set {
                this.imageZoneIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        public int SourcePage {
            get {
                return this.sourcePageField;
            }
            set {
                this.sourcePageField = value;
            }
        }
        
        /// <remarks/>
        public decimal Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public decimal Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        public decimal Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImageFileFormat {
            get {
                return this.imageFileFormatField;
            }
            set {
                this.imageFileFormatField = value;
            }
        }
        
        /// <remarks/>
        public int OutputPageNumber {
            get {
                return this.outputPageNumberField;
            }
            set {
                this.outputPageNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Layout")]
    public partial class ImageCluster {
        
        private int imageClusterIdentifierField;
        
        private int sequenceField;
        
        private string nameField;
        
        private ImageZone[] imageZonesField;
        
        /// <remarks/>
        public int ImageClusterIdentifier {
            get {
                return this.imageClusterIdentifierField;
            }
            set {
                this.imageClusterIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ImageZone[] ImageZones {
            get {
                return this.imageZonesField;
            }
            set {
                this.imageZonesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkSchemeStructureReceipt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkSchemeAnswerReceipt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LayoutReceipt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductReceipt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03")]
    public partial class ScorisWSReceipt {
        
        private bool successField;
        
        private string errorField;
        
        private long returnCodeField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public long ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03")]
    public partial class MarkSchemeStructureReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03")]
    public partial class MarkSchemeAnswerReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03")]
    public partial class LayoutReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/WebServices/AssessmentStructureWS/2009/03")]
    public partial class ProductReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class ExamCharacteristic {
        
        private string descriptorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class QuestionPaperCharacteristic {
        
        private string descriptorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class ProductArgumentsSession {
        
        private string nameField;
        
        private string sessionIdentifierField;
        
        private string timeframeField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        private System.Nullable<System.DateTime> passwordResetDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionIdentifier {
            get {
                return this.sessionIdentifierField;
            }
            set {
                this.sessionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Timeframe {
            get {
                return this.timeframeField;
            }
            set {
                this.timeframeField = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PasswordResetDate {
            get {
                return this.passwordResetDateField;
            }
            set {
                this.passwordResetDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class ProductArgumentsProduct {
        
        private string businessStreamIndentifierField;
        
        private string qualificationShortNameField;
        
        private string assessmentIndentifierField;
        
        private string assessmentNameField;
        
        private int assessmentVersionField;
        
        private string componentIdentifierField;
        
        private string componentNameField;
        
        private int componentVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIndentifier {
            get {
                return this.businessStreamIndentifierField;
            }
            set {
                this.businessStreamIndentifierField = value;
            }
        }
        
        /// <remarks/>
        public string QualificationShortName {
            get {
                return this.qualificationShortNameField;
            }
            set {
                this.qualificationShortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentIndentifier {
            get {
                return this.assessmentIndentifierField;
            }
            set {
                this.assessmentIndentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentName {
            get {
                return this.assessmentNameField;
            }
            set {
                this.assessmentNameField = value;
            }
        }
        
        /// <remarks/>
        public int AssessmentVersion {
            get {
                return this.assessmentVersionField;
            }
            set {
                this.assessmentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComponentIdentifier {
            get {
                return this.componentIdentifierField;
            }
            set {
                this.componentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComponentName {
            get {
                return this.componentNameField;
            }
            set {
                this.componentNameField = value;
            }
        }
        
        /// <remarks/>
        public int ComponentVersion {
            get {
                return this.componentVersionField;
            }
            set {
                this.componentVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Product")]
    public partial class ProductArgumentsExam {
        
        private System.DateTime archiveDateField;
        
        private bool archiveDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private string endDatePartField;
        
        private System.DateTime startDateField;
        
        private string startDatePartField;
        
        private ExamCharacteristic[] examCharacteristicsField;
        
        /// <remarks/>
        public System.DateTime ArchiveDate {
            get {
                return this.archiveDateField;
            }
            set {
                this.archiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArchiveDateSpecified {
            get {
                return this.archiveDateFieldSpecified;
            }
            set {
                this.archiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDatePart {
            get {
                return this.endDatePartField;
            }
            set {
                this.endDatePartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StartDatePart {
            get {
                return this.startDatePartField;
            }
            set {
                this.startDatePartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExamCharacteristic[] ExamCharacteristics {
            get {
                return this.examCharacteristicsField;
            }
            set {
                this.examCharacteristicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Layout")]
    public partial class LayoutArguments {
        
        private string businessStreamIdentifierField;
        
        private string questionPaperIdentifierField;
        
        private ImageCluster[] imageClustersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionPaperIdentifier {
            get {
                return this.questionPaperIdentifierField;
            }
            set {
                this.questionPaperIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ImageCluster[] ImageClusters {
            get {
                return this.imageClustersField;
            }
            set {
                this.imageClustersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeAnswer")]
    public partial class MarkSchemeAnswerArguments {
        
        private string businessStreamIdentifierField;
        
        private string questionPaperIdentifierField;
        
        private string questionItemGroupIdentifierField;
        
        private MarkScheme[] markSchemesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionPaperIdentifier {
            get {
                return this.questionPaperIdentifierField;
            }
            set {
                this.questionPaperIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionItemGroupIdentifier {
            get {
                return this.questionItemGroupIdentifierField;
            }
            set {
                this.questionItemGroupIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MarkScheme[] MarkSchemes {
            get {
                return this.markSchemesField;
            }
            set {
                this.markSchemesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkSchemeStructure")]
    public partial class MarkSchemeStructureArguments {
        
        private string businessStreamIdentifierField;
        
        private string questionPaperIdentifierField;
        
        private QuestionItemGroup[] questionItemGroupsField;
        
        private MarkingCluster[] markingClustersField;
        
        private MarkingItem[] markingItemsField;
        
        private MarkType[] markTypesField;
        
        private MarkScheme1[] markSchemesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionPaperIdentifier {
            get {
                return this.questionPaperIdentifierField;
            }
            set {
                this.questionPaperIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public QuestionItemGroup[] QuestionItemGroups {
            get {
                return this.questionItemGroupsField;
            }
            set {
                this.questionItemGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MarkingCluster[] MarkingClusters {
            get {
                return this.markingClustersField;
            }
            set {
                this.markingClustersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MarkingItem[] MarkingItems {
            get {
                return this.markingItemsField;
            }
            set {
                this.markingItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MarkType[] MarkTypes {
            get {
                return this.markTypesField;
            }
            set {
                this.markTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MarkScheme1[] MarkSchemes {
            get {
                return this.markSchemesField;
            }
            set {
                this.markSchemesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ProductCompletedEventHandler(object sender, ProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LayoutCompletedEventHandler(object sender, LayoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LayoutReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LayoutReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MarkSchemeAnswerCompletedEventHandler(object sender, MarkSchemeAnswerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkSchemeAnswerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarkSchemeAnswerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MarkSchemeAnswerReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MarkSchemeAnswerReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MarkSchemeStructureCompletedEventHandler(object sender, MarkSchemeStructureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkSchemeStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarkSchemeStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MarkSchemeStructureReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MarkSchemeStructureReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591