//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDEWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gder61uat-webservice.assessor.rm.com/AssessmentStructureWS.asmx")]
        public string GDEWebService_AssessmentStructureWS_AssessmentStructureWS {
            get {
                return ((string)(this["GDEWebService_AssessmentStructureWS_AssessmentStructureWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gder61uat-webservice.assessor.rm.com/MarkerProvisioningWS.asmx")]
        public string GDEWebService_MarkerProvisioningWS_MarkerProvisioningWS {
            get {
                return ((string)(this["GDEWebService_MarkerProvisioningWS_MarkerProvisioningWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gder61uat-webservice.assessor.rm.com/SessionCompositionWS.asmx")]
        public string GDEWebService_SessionCompositionWS_SessionCompositionWS {
            get {
                return ((string)(this["GDEWebService_SessionCompositionWS_SessionCompositionWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gder61uat-scanning.assessor.rm.com/rmscanningwebws.asmx")]
        public string GDEWebService_ScanningWebWS_rmScanningWebWS {
            get {
                return ((string)(this["GDEWebService_ScanningWebWS_rmScanningWebWS"]));
            }
        }
    }
}
