//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GDEWebService.SessionCompositionWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SessionCompositionWSSoap", Namespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScorisWSReceipt))]
    public partial class SessionCompositionWS : Microsoft.Web.Services3.WebServicesClientProtocol{
        
        private System.Threading.SendOrPostCallback CandidateEntriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CandidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CentresOperationCompleted;
        
        private System.Threading.SendOrPostCallback PacketsOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkerResponsibilitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SessionCompositionWS() {
            this.Url = global::GDEWebService.Properties.Settings.Default.GDEWebService_SessionCompositionWS_SessionCompositionWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CandidateEntriesCompletedEventHandler CandidateEntriesCompleted;
        
        /// <remarks/>
        public event CandidateCompletedEventHandler CandidateCompleted;
        
        /// <remarks/>
        public event CentresCompletedEventHandler CentresCompleted;
        
        /// <remarks/>
        public event PacketsCompletedEventHandler PacketsCompleted;
        
        /// <remarks/>
        public event MarkerResponsibilitiesCompletedEventHandler MarkerResponsibilitiesCompleted;
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03/CandidateEntries" +
            "", RequestNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", ResponseNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CandidateEntriesReceipt CandidateEntries(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/CandidateEntries")] CandidateEntriesArguments CandidateEntriesArguments) {
            object[] results = this.Invoke("CandidateEntries", new object[] {
                        RMKey,
                        CandidateEntriesArguments});
            return ((CandidateEntriesReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void CandidateEntriesAsync(string RMKey, CandidateEntriesArguments CandidateEntriesArguments) {
            this.CandidateEntriesAsync(RMKey, CandidateEntriesArguments, null);
        }
        
        /// <remarks/>
        public void CandidateEntriesAsync(string RMKey, CandidateEntriesArguments CandidateEntriesArguments, object userState) {
            if ((this.CandidateEntriesOperationCompleted == null)) {
                this.CandidateEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCandidateEntriesOperationCompleted);
            }
            this.InvokeAsync("CandidateEntries", new object[] {
                        RMKey,
                        CandidateEntriesArguments}, this.CandidateEntriesOperationCompleted, userState);
        }
        
        private void OnCandidateEntriesOperationCompleted(object arg) {
            if ((this.CandidateEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CandidateEntriesCompleted(this, new CandidateEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03/Candidate", RequestNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", ResponseNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CandidateReceipt Candidate(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Candidate")] CandidateArguments CandidateArguments) {
            object[] results = this.Invoke("Candidate", new object[] {
                        RMKey,
                        CandidateArguments});
            return ((CandidateReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void CandidateAsync(string RMKey, CandidateArguments CandidateArguments) {
            this.CandidateAsync(RMKey, CandidateArguments, null);
        }
        
        /// <remarks/>
        public void CandidateAsync(string RMKey, CandidateArguments CandidateArguments, object userState) {
            if ((this.CandidateOperationCompleted == null)) {
                this.CandidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCandidateOperationCompleted);
            }
            this.InvokeAsync("Candidate", new object[] {
                        RMKey,
                        CandidateArguments}, this.CandidateOperationCompleted, userState);
        }
        
        private void OnCandidateOperationCompleted(object arg) {
            if ((this.CandidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CandidateCompleted(this, new CandidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03/Centres", RequestNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", ResponseNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CentresReceipt Centres(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Centres")] CentreArguments CentreArguments) {
            object[] results = this.Invoke("Centres", new object[] {
                        RMKey,
                        CentreArguments});
            return ((CentresReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void CentresAsync(string RMKey, CentreArguments CentreArguments) {
            this.CentresAsync(RMKey, CentreArguments, null);
        }
        
        /// <remarks/>
        public void CentresAsync(string RMKey, CentreArguments CentreArguments, object userState) {
            if ((this.CentresOperationCompleted == null)) {
                this.CentresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCentresOperationCompleted);
            }
            this.InvokeAsync("Centres", new object[] {
                        RMKey,
                        CentreArguments}, this.CentresOperationCompleted, userState);
        }
        
        private void OnCentresOperationCompleted(object arg) {
            if ((this.CentresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CentresCompleted(this, new CentresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03/Packets", RequestNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", ResponseNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PacketsReceipt Packets(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Packets")] PacketArguments PacketArguments) {
            object[] results = this.Invoke("Packets", new object[] {
                        RMKey,
                        PacketArguments});
            return ((PacketsReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void PacketsAsync(string RMKey, PacketArguments PacketArguments) {
            this.PacketsAsync(RMKey, PacketArguments, null);
        }
        
        /// <remarks/>
        public void PacketsAsync(string RMKey, PacketArguments PacketArguments, object userState) {
            if ((this.PacketsOperationCompleted == null)) {
                this.PacketsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPacketsOperationCompleted);
            }
            this.InvokeAsync("Packets", new object[] {
                        RMKey,
                        PacketArguments}, this.PacketsOperationCompleted, userState);
        }
        
        private void OnPacketsOperationCompleted(object arg) {
            if ((this.PacketsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PacketsCompleted(this, new PacketsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03/MarkerResponsibi" +
            "lities", RequestNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", ResponseNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MarkerResponsibilitiesReceipt MarkerResponsibilities(string RMKey, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")] MarkerResponsibilitiesArguments MarkerResponsibilitiesArguments) {
            object[] results = this.Invoke("MarkerResponsibilities", new object[] {
                        RMKey,
                        MarkerResponsibilitiesArguments});
            return ((MarkerResponsibilitiesReceipt)(results[0]));
        }
        
        /// <remarks/>
        public void MarkerResponsibilitiesAsync(string RMKey, MarkerResponsibilitiesArguments MarkerResponsibilitiesArguments) {
            this.MarkerResponsibilitiesAsync(RMKey, MarkerResponsibilitiesArguments, null);
        }
        
        /// <remarks/>
        public void MarkerResponsibilitiesAsync(string RMKey, MarkerResponsibilitiesArguments MarkerResponsibilitiesArguments, object userState) {
            if ((this.MarkerResponsibilitiesOperationCompleted == null)) {
                this.MarkerResponsibilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkerResponsibilitiesOperationCompleted);
            }
            this.InvokeAsync("MarkerResponsibilities", new object[] {
                        RMKey,
                        MarkerResponsibilitiesArguments}, this.MarkerResponsibilitiesOperationCompleted, userState);
        }
        
        private void OnMarkerResponsibilitiesOperationCompleted(object arg) {
            if ((this.MarkerResponsibilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkerResponsibilitiesCompleted(this, new MarkerResponsibilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03/Ping", RequestNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", ResponseNamespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/CandidateEntries")]
    public partial class CandidateEntriesArguments {
        
        private string businessStreamIdentifierField;
        
        private string sessionIdentifierField;
        
        private string assessmentIdentifierField;
        
        private int assessmentVersionField;
        
        private string componentIdentifierField;
        
        private int componentVersionField;
        
        private string centreIdentifierField;
        
        private string centrePartIdentifierField;
        
        private CandidateEntry[] candidateEntriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionIdentifier {
            get {
                return this.sessionIdentifierField;
            }
            set {
                this.sessionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentIdentifier {
            get {
                return this.assessmentIdentifierField;
            }
            set {
                this.assessmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int AssessmentVersion {
            get {
                return this.assessmentVersionField;
            }
            set {
                this.assessmentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComponentIdentifier {
            get {
                return this.componentIdentifierField;
            }
            set {
                this.componentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int ComponentVersion {
            get {
                return this.componentVersionField;
            }
            set {
                this.componentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentreIdentifier {
            get {
                return this.centreIdentifierField;
            }
            set {
                this.centreIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string CentrePartIdentifier {
            get {
                return this.centrePartIdentifierField;
            }
            set {
                this.centrePartIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CandidateEntries", IsNullable=true)]
        public CandidateEntry[] CandidateEntries {
            get {
                return this.candidateEntriesField;
            }
            set {
                this.candidateEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/CandidateEntries")]
    public partial class CandidateEntry {
        
        private string uniqueCandidateIdentifierField;
        
        private string centreCandidateIdentifierField;
        
        private string candidateNameField;
        
        private string genderField;
        
        private System.DateTime dOBField;
        
        private bool dOBFieldSpecified;
        
        private System.DateTime markingTargetDateField;
        
        private System.DateTime testDateField;
        
        private CandidateAttribute[] attributesField;
        
        private SpecialistResponseMarkingType specialistResponseMarkingTypeField;
        
        private string attendanceStatusField;
        
        private int allocationPriorityField;
        
        private bool allocationPriorityFieldSpecified;
        
        private bool removeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UniqueCandidateIdentifier {
            get {
                return this.uniqueCandidateIdentifierField;
            }
            set {
                this.uniqueCandidateIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentreCandidateIdentifier {
            get {
                return this.centreCandidateIdentifierField;
            }
            set {
                this.centreCandidateIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CandidateName {
            get {
                return this.candidateNameField;
            }
            set {
                this.candidateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOBSpecified {
            get {
                return this.dOBFieldSpecified;
            }
            set {
                this.dOBFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MarkingTargetDate {
            get {
                return this.markingTargetDateField;
            }
            set {
                this.markingTargetDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TestDate {
            get {
                return this.testDateField;
            }
            set {
                this.testDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attributes")]
        public CandidateAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public SpecialistResponseMarkingType SpecialistResponseMarkingType {
            get {
                return this.specialistResponseMarkingTypeField;
            }
            set {
                this.specialistResponseMarkingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AttendanceStatus {
            get {
                return this.attendanceStatusField;
            }
            set {
                this.attendanceStatusField = value;
            }
        }
        
        /// <remarks/>
        public int AllocationPriority {
            get {
                return this.allocationPriorityField;
            }
            set {
                this.allocationPriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllocationPrioritySpecified {
            get {
                return this.allocationPriorityFieldSpecified;
            }
            set {
                this.allocationPriorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/CandidateEntries")]
    public partial class CandidateAttribute {
        
        private string descriptorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")]
    public partial class EligibilityCentre {
        
        private string centreIdentifierField;
        
        private string centrePartIdentifierField;
        
        private string eligibilityTypeField;
        
        private string[] candidatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentreIdentifier {
            get {
                return this.centreIdentifierField;
            }
            set {
                this.centreIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentrePartIdentifier {
            get {
                return this.centrePartIdentifierField;
            }
            set {
                this.centrePartIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EligibilityType {
            get {
                return this.eligibilityTypeField;
            }
            set {
                this.eligibilityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CentreCandidateIdentifier")]
        public string[] Candidates {
            get {
                return this.candidatesField;
            }
            set {
                this.candidatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")]
    public partial class TargetAttribute {
        
        private string descriptorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")]
    public partial class Target {
        
        private string targetTypeField;
        
        private int maximumMarkingCountField;
        
        private System.DateTime markingCompletionDateField;
        
        private TargetAttribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TargetType {
            get {
                return this.targetTypeField;
            }
            set {
                this.targetTypeField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumMarkingCount {
            get {
                return this.maximumMarkingCountField;
            }
            set {
                this.maximumMarkingCountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MarkingCompletionDate {
            get {
                return this.markingCompletionDateField;
            }
            set {
                this.markingCompletionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attributes")]
        public TargetAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")]
    public partial class ParentMarker {
        
        private string markerIdentifierField;
        
        private string markerTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkerIdentifier {
            get {
                return this.markerIdentifierField;
            }
            set {
                this.markerIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkerType {
            get {
                return this.markerTypeField;
            }
            set {
                this.markerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")]
    public partial class MarkerAttribute {
        
        private string descriptorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")]
    public partial class Marker {
        
        private string markerIdentifierField;
        
        private string markerTypeField;
        
        private string roleNameField;
        
        private int priorityField;
        
        private bool downloadAtypicalsField;
        
        private bool downloadAtypicalsFieldSpecified;
        
        private bool standardisationTeamIndicatorField;
        
        private bool standardisationTeamIndicatorFieldSpecified;
        
        private MarkerAttribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkerIdentifier {
            get {
                return this.markerIdentifierField;
            }
            set {
                this.markerIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MarkerType {
            get {
                return this.markerTypeField;
            }
            set {
                this.markerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public bool DownloadAtypicals {
            get {
                return this.downloadAtypicalsField;
            }
            set {
                this.downloadAtypicalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DownloadAtypicalsSpecified {
            get {
                return this.downloadAtypicalsFieldSpecified;
            }
            set {
                this.downloadAtypicalsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool StandardisationTeamIndicator {
            get {
                return this.standardisationTeamIndicatorField;
            }
            set {
                this.standardisationTeamIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StandardisationTeamIndicatorSpecified {
            get {
                return this.standardisationTeamIndicatorFieldSpecified;
            }
            set {
                this.standardisationTeamIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attributes")]
        public MarkerAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Packets")]
    public partial class Packet {
        
        private string packetBarcodeField;
        
        private string markerIdentifierField;
        
        private string markerTypeField;
        
        private string surnameField;
        
        private string initialsField;
        
        private int centresplitnumberField;
        
        private bool centresplitnumberFieldSpecified;
        
        private string firstCentreCandidateIdentifierField;
        
        private string lastCentreCandidateIdentifierField;
        
        private string packetstatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PacketBarcode {
            get {
                return this.packetBarcodeField;
            }
            set {
                this.packetBarcodeField = value;
            }
        }
        
        /// <remarks/>
        public string MarkerIdentifier {
            get {
                return this.markerIdentifierField;
            }
            set {
                this.markerIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string MarkerType {
            get {
                return this.markerTypeField;
            }
            set {
                this.markerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public int Centresplitnumber {
            get {
                return this.centresplitnumberField;
            }
            set {
                this.centresplitnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CentresplitnumberSpecified {
            get {
                return this.centresplitnumberFieldSpecified;
            }
            set {
                this.centresplitnumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string FirstCentreCandidateIdentifier {
            get {
                return this.firstCentreCandidateIdentifierField;
            }
            set {
                this.firstCentreCandidateIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string LastCentreCandidateIdentifier {
            get {
                return this.lastCentreCandidateIdentifierField;
            }
            set {
                this.lastCentreCandidateIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Packetstatus {
            get {
                return this.packetstatusField;
            }
            set {
                this.packetstatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/Candidate")]
    public partial class ResponseFile {
        
        private string responseFileIdentifierField;
        
        private byte[] responseFileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResponseFileIdentifier {
            get {
                return this.responseFileIdentifierField;
            }
            set {
                this.responseFileIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ResponseFileContent {
            get {
                return this.responseFileContentField;
            }
            set {
                this.responseFileContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarkerResponsibilitiesReceipt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PacketsReceipt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CentresReceipt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CandidateReceipt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CandidateEntriesReceipt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03")]
    public partial class ScorisWSReceipt {
        
        private bool successField;
        
        private string errorField;
        
        private long returnCodeField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public long ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03")]
    public partial class MarkerResponsibilitiesReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03")]
    public partial class PacketsReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03")]
    public partial class CentresReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03")]
    public partial class CandidateReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/ScorisWebServices/SessionCompositionWS/2009/03")]
    public partial class CandidateEntriesReceipt : ScorisWSReceipt {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.rm.com/scoris/schemas/2009/03/CandidateEntries")]
    public partial class SpecialistResponseMarkingType {
        
        private string typeField;
        
        private string[] questionItemGroupIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuestionItemGroupIdentifier", IsNullable=true)]
        public string[] QuestionItemGroupIdentifier {
            get {
                return this.questionItemGroupIdentifierField;
            }
            set {
                this.questionItemGroupIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Candidate")]
    public partial class CandidateArguments {
        
        private string businessStreamIdentifierField;
        
        private string sessionIdentifierField;
        
        private string assessmentIdentifierField;
        
        private int assessmentVersionField;
        
        private string componentIdentifierField;
        
        private int componentVersionField;
        
        private string questionPaperIdentifierField;
        
        private string centreIdentifierField;
        
        private string centrePartIdentifierField;
        
        private string centreCandidateIdentifierField;
        
        private object additionalInfoField;
        
        private ResponseFile[] responseFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionIdentifier {
            get {
                return this.sessionIdentifierField;
            }
            set {
                this.sessionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentIdentifier {
            get {
                return this.assessmentIdentifierField;
            }
            set {
                this.assessmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int AssessmentVersion {
            get {
                return this.assessmentVersionField;
            }
            set {
                this.assessmentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComponentIdentifier {
            get {
                return this.componentIdentifierField;
            }
            set {
                this.componentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int ComponentVersion {
            get {
                return this.componentVersionField;
            }
            set {
                this.componentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuestionPaperIdentifier {
            get {
                return this.questionPaperIdentifierField;
            }
            set {
                this.questionPaperIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentreIdentifier {
            get {
                return this.centreIdentifierField;
            }
            set {
                this.centreIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string CentrePartIdentifier {
            get {
                return this.centrePartIdentifierField;
            }
            set {
                this.centrePartIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentreCandidateIdentifier {
            get {
                return this.centreCandidateIdentifierField;
            }
            set {
                this.centreCandidateIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object AdditionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseFiles")]
        public ResponseFile[] ResponseFiles {
            get {
                return this.responseFilesField;
            }
            set {
                this.responseFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Centres")]
    public partial class CentreArguments {
        
        private string businessStreamIdentifierField;
        
        private string sessionIdentifierField;
        
        private string assessmentIdentifierField;
        
        private int assessmentVersionField;
        
        private string componentIdentifierField;
        
        private int componentVersionField;
        
        private string centreIdentifierField;
        
        private string centrePartIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionIdentifier {
            get {
                return this.sessionIdentifierField;
            }
            set {
                this.sessionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentIdentifier {
            get {
                return this.assessmentIdentifierField;
            }
            set {
                this.assessmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int AssessmentVersion {
            get {
                return this.assessmentVersionField;
            }
            set {
                this.assessmentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComponentIdentifier {
            get {
                return this.componentIdentifierField;
            }
            set {
                this.componentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int ComponentVersion {
            get {
                return this.componentVersionField;
            }
            set {
                this.componentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentreIdentifier {
            get {
                return this.centreIdentifierField;
            }
            set {
                this.centreIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string CentrePartIdentifier {
            get {
                return this.centrePartIdentifierField;
            }
            set {
                this.centrePartIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/Packets")]
    public partial class PacketArguments {
        
        private string businessStreamIdentifierField;
        
        private string sessionIdentifierField;
        
        private string centreIdentifierField;
        
        private string assessmentIdentifierField;
        
        private int assessmentVersionField;
        
        private string componentIdentifierField;
        
        private int componentVersionField;
        
        private string centrePartIdentifierField;
        
        private bool isScanningScriptCreatedField;
        
        private Packet[] packetsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionIdentifier {
            get {
                return this.sessionIdentifierField;
            }
            set {
                this.sessionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CentreIdentifier {
            get {
                return this.centreIdentifierField;
            }
            set {
                this.centreIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentIdentifier {
            get {
                return this.assessmentIdentifierField;
            }
            set {
                this.assessmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int AssessmentVersion {
            get {
                return this.assessmentVersionField;
            }
            set {
                this.assessmentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComponentIdentifier {
            get {
                return this.componentIdentifierField;
            }
            set {
                this.componentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int ComponentVersion {
            get {
                return this.componentVersionField;
            }
            set {
                this.componentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string CentrePartIdentifier {
            get {
                return this.centrePartIdentifierField;
            }
            set {
                this.centrePartIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public bool IsScanningScriptCreated {
            get {
                return this.isScanningScriptCreatedField;
            }
            set {
                this.isScanningScriptCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Packets", IsNullable=false)]
        public Packet[] Packets {
            get {
                return this.packetsField;
            }
            set {
                this.packetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.rm.com/scoris/schemas/2009/03/MarkerResponsibilities")]
    public partial class MarkerResponsibilitiesArguments {
        
        private string businessStreamIdentifierField;
        
        private string sessionIdentifierField;
        
        private string assessmentIdentifierField;
        
        private int assessmentVersionField;
        
        private string componentIdentifierField;
        
        private int componentVersionField;
        
        private int questionItemGroupIdentifierField;
        
        private bool questionItemGroupIdentifierFieldSpecified;
        
        private bool removeMarkerField;
        
        private bool removeMarkerFieldSpecified;
        
        private Marker markerField;
        
        private ParentMarker parentMarkerField;
        
        private ParentMarker standardisationParentMarkerField;
        
        private Target[] targetsField;
        
        private string[] specialistResponseMarkingTypesField;
        
        private EligibilityCentre[] centresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BusinessStreamIdentifier {
            get {
                return this.businessStreamIdentifierField;
            }
            set {
                this.businessStreamIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionIdentifier {
            get {
                return this.sessionIdentifierField;
            }
            set {
                this.sessionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AssessmentIdentifier {
            get {
                return this.assessmentIdentifierField;
            }
            set {
                this.assessmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int AssessmentVersion {
            get {
                return this.assessmentVersionField;
            }
            set {
                this.assessmentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ComponentIdentifier {
            get {
                return this.componentIdentifierField;
            }
            set {
                this.componentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public int ComponentVersion {
            get {
                return this.componentVersionField;
            }
            set {
                this.componentVersionField = value;
            }
        }
        
        /// <remarks/>
        public int QuestionItemGroupIdentifier {
            get {
                return this.questionItemGroupIdentifierField;
            }
            set {
                this.questionItemGroupIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuestionItemGroupIdentifierSpecified {
            get {
                return this.questionItemGroupIdentifierFieldSpecified;
            }
            set {
                this.questionItemGroupIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool RemoveMarker {
            get {
                return this.removeMarkerField;
            }
            set {
                this.removeMarkerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemoveMarkerSpecified {
            get {
                return this.removeMarkerFieldSpecified;
            }
            set {
                this.removeMarkerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Marker Marker {
            get {
                return this.markerField;
            }
            set {
                this.markerField = value;
            }
        }
        
        /// <remarks/>
        public ParentMarker ParentMarker {
            get {
                return this.parentMarkerField;
            }
            set {
                this.parentMarkerField = value;
            }
        }
        
        /// <remarks/>
        public ParentMarker StandardisationParentMarker {
            get {
                return this.standardisationParentMarkerField;
            }
            set {
                this.standardisationParentMarkerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Target[] Targets {
            get {
                return this.targetsField;
            }
            set {
                this.targetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SpecialistResponseMarkingType", IsNullable=false)]
        public string[] SpecialistResponseMarkingTypes {
            get {
                return this.specialistResponseMarkingTypesField;
            }
            set {
                this.specialistResponseMarkingTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Centre", IsNullable=false)]
        public EligibilityCentre[] Centres {
            get {
                return this.centresField;
            }
            set {
                this.centresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CandidateEntriesCompletedEventHandler(object sender, CandidateEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CandidateEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CandidateEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CandidateEntriesReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CandidateEntriesReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CandidateCompletedEventHandler(object sender, CandidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CandidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CandidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CandidateReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CandidateReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CentresCompletedEventHandler(object sender, CentresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CentresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CentresReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CentresReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PacketsCompletedEventHandler(object sender, PacketsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PacketsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PacketsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PacketsReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PacketsReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MarkerResponsibilitiesCompletedEventHandler(object sender, MarkerResponsibilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkerResponsibilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarkerResponsibilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MarkerResponsibilitiesReceipt Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MarkerResponsibilitiesReceipt)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591